version: '3.8'
services:
  api:
    build: .
    ports:
      - "4000:4000"
    env_file: .env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongo
      - ml-service
  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
  ml-service:
    build: ./python-ml-stub
    ports:
      - "5000:5000"
volumes:
  mongo-data: